### ISSUE TITLE
Отображение задач

### ISSUE THREAD

**Issue by Gleb417** [ShortWhale417/CRMItRoom18#8]
Интерфейс для отображения задач из GitHub и созданных в системе.
Реализация фильтров и сортировок.
Дописать отоброжение валидатции по срокам

**Comment by itroom18-user** [comment]
![image](https://github.com/user-attachments/assets/2e873b40-d039-425e-a0ed-af432993a70c)

**Comment by Kokorin-Danil** [comment]
![Image](https://github.com/user-attachments/assets/864de6f8-3f75-44c7-b38c-25ca8ab62fe6)
